-- Change settings according to the documented changes from espen
DELETE FROM `Settings`;
INSERT INTO `Settings` (`BIThresholdLower`, `BIThresholdUpper`, `maxXAxisIntervalDays`, `BIImgHeader`, `BIChartHeader`, `AIChartHeader`, `BIImgLabelLow`, `BIImgLabelHigh`, `BIChartSpectrumLabelLow`, `BIChartSpectrumLabelMedium`, `BIChartSpectrumLabelHigh`, `BIChartLineText`, `AIChartLineText`, `BIImgHelpTooltipText`, `BIChartHelpTooltipText`, `AIChartHelpTooltipText`) VALUES
(-0.500, 0.500, 60, 'Din balanse', 'Din balanse over tid', 'Din aktivitet over tid', 'Dårlig', 'God', 'Dårlig', 'Medium', 'God', 'Gjennomsnittlig', 'Nasjonale anbefalinger', ' Denne grafen representerer din balanseverdi. Denne verdien beregnet ut fra målingene fra sensoren i beltet ditt og påvirkes av <i>hvordan</i> du beveger deg når du går. Har du god balanse har du mere rytmiske bevegelser når du går enn hvis du har dårlig balanse.  Balanseverdien blir beregnet på bakgrunn av alle gå-periodene i løpet av en uke som har over 30 sekunders varighet. Dersom du har en god balanse når du går har du en lavere risiko for å falle. Grønt betyr god balanse, og rød betyr dårlig.', '  Dette diagrammet viser din ukentlige balanse. Den stiplede linjen viser gjennomsnittet for din balanse i forhold til alder, høyde, vekt og kjønn du har oppgitt. På dette diagrammet kan du følge hvordan balansen din endrer seg fra uke til uke.', '  Dette diagrammet viser din ukentlige gåtid. Den stiplede linjen viser de nasjonale helseanbefalingene for fysisk aktivitet for personer i alderen 65+ (2014).');
-- delete everything that depends on the exercise IDs
DELETE FROM `ExerciseGroups`;
DELETE FROM `FeedbackMsgDefault`;
-- delete the exercises
DELETE FROM `Exercises`;
--insert new exercises
-- indexsection: -1 dårlig 0 middels 1 god balanse
INSERT INTO `Exercises` (`exerciseID`, `indexSection`, `title`, `imgFilename`, `textPreList`, `textList`, `textPostList`, `textPostListBold`, `exerciseGroupID`) VALUES
-- Styrkeøvelser
    (1, -1, 'Ankelstyrke sittende', 'ankelstyrke.png', 'Sitt oppreist ytterst på stolen, med hoftebreddes avstand mellom føttene. Flytt føttene litt frem slik at hælene kommer godt foran knærne.', 'Roter føttene innover. Hold posisjonen i 1-2 sekunder og senk føttene ned til gulvet igjen.;Roter så føttene utover og løft tærne ut til siden. Hold posisjonen i 1-2 sekunder, og senk føttene ned til gulvet.;Gjennomfør hele bevegelsen med en jevn flyt.', NULL, 'Gjenta 10 ganger.', 1),
    (2, -1, 'Sittende løft av tærne', 'sitteloftetaerne.png', 'Sitt fram på stolen med riktig holdning, føttene i hoftebreddes avstand og anklene under knærne. Hold på siden av stolen eller ha håndflatene på lårene.', 'Løft tærne raskt og kontrollert opp.;Hold 1-2 sekund.;Senk tærne langsomt og kontrollert ned igjen.', NULL, 'Gjenta øvelsen 10 ganger.', 1),
    (3, -1, 'Reise seg og sette seg', 'reiseogsetteseg.png', 'Sitt oppreist ytterst på stolen (gjerne med armer i kryss over brystet).', 'Bøy overkroppen fram og reis deg raskt og kontrollert opp.;Sett deg kontrollert og langsomt ned igjen.', NULL, 'Gjenta øvelsen 10 ganger.', 1),
    (4, -1, 'Stå på tå', 'staapaataa.png', 'Stå oppreist med hoftebreddes avstand mellom føttene. Støtt deg til en stol eller kjøkkenbenken ved behov.', 'Løft deg raskt og kontrollert opp på tå.;Hold 1-2 sekund.;Senk hælene langsomt og kontrollert ned igjen.', NULL, 'Gjenta øvelsen 10 ganger.', 1),
    (5, -1, 'Stå på hælene', 'staapaahaelene.png', 'Stå oppreist med hoftebreddes avstand mellom føttene. Støtt deg til en stol eller kjøkkenbenken ved behov.', 'Løft deg raskt og kontrollert opp på hælene.;Hold 1-2 sekund.;Senk tærne langsomt og kontrollert ned igjen.', NULL, 'Gjenta øvelsen 10 ganger.', 1),
    (6, 0, 'Steg til siden', 'stegtilsiden.png', 'Stå oppreist med samlede ben, og ha en rett holdning i overkroppen. Hold deg fast i en stol eller kjøkkenbenken ved behov.', 'Ta et steg til siden med det ytterste benet, plasser foten flatt på gulvet med bøyd kne.;Skyv lett i fra og bring benet tilbake til utgangspunktet.', NULL, 'Gjenta 10 ganger på hvert ben.', 1),
    (7, 0, 'Utfall med støtte', 'utfallmedstoette.png', 'Stå med samlede ben. Støtt deg til en stol eller kjøkkenbenken ved behov.', 'Ta et langt steg framover og skyv kroppsvekten over på det fremste benet.;Skyv i fra og flytt benet tilbake til utgangspunktet.', NULL, 'Gjenta 10 ganger på hvert ben.', 1),
    (8, 0, 'Knebøy med støtte', 'kneboeymedstoette.png', 'Stå oppreist med hoftebreddes avstand mellom føttene. Støtt deg til en stol eller kjøkkenbenken ved behov.',' Knær og tær skal peke frem og litt ut til siden.;Bøy i hofter og knær som om at du skulle ha satt deg på en stol.;Reis deg opp til utgangsposisjonen.', NULL, 'Gjenta 10 ganger', 1),
    (9, 0, 'Styrke utside hofte', 'styrkeutsidehofte.png', 'Stå oppreist med hoftebreddes avstand mellom føttene. Bruk en stol eller kjøkkenbenken som støtte.','Løft benet kontrollert ut til siden mens tærne peker framover.;Unngå å lene overkroppen frem eller mot siden.;Hold i 1-2 sekunder.;Senk benet sakte.', NULL, 'Gjenta 10 ganger på hver fot.', 1),
    (10, 1, 'Knebøy uten støtte', 'kneboeyutenstoette.png', 'Stå oppreist med hoftebreddes avstand mellom føttene. Reduser støtten; til ei hånd, til en finger, til ingen støtte.','Knær og tær skal peke frem og litt ut til siden.;Bøy i hofter og knær som om at du skulle ha satt deg på en stol.;Reis deg opp til utgangsposisjonen. ', NULL, 'Gjenta 10 ganger', 1),
    (11, 1, 'Utfall uten støtte', 'utfallutenstoette.png', 'Stå oppreist med samlede ben, og ha en rett holdning i overkroppen. Reduser støtten; til ei hånd, til en finger, til ingen støtte.','Ta et langt steg framover og skyv kroppsvekten over på det fremste benet.;Skyv i fra og flytt benet tilbake til utgangspunktet.', NULL, 'Gjenta 10 ganger på hvert ben', 1),
    (12, 1, 'Reise seg og sette seg uten støtte', 'reiseogsettesegutenstoette.png', 'Sitt oppreist ytterst på stolen (gjerne med armer i kryss over brystet). Reduser støtten; til ei hånd, til en finger, til ingen støtte.','Bøy overkroppen fram og reis deg raskt og kontrollert opp.;Stans bevegelsen og hold i 2-3 sekunder på veg ned.;Sett deg kontrollert og langsomt ned igjen.', NULL, 'Gjenta øvelsen 10 ganger.', 1),
    (13, 1, 'Steg ut til siden', 'steguttilsiden.png', 'Stå oppreist med samlede ben, og ha en rett holdning i overkroppen.  Reduser støtten; til ei hånd, til en finger, til ingen støtte.','Ta et steg ut til siden med det ytterste benet, plasser foten flatt på gulvet med bøyd kne.;Skyv lett i fra og bring benet tilbake til utgangspunktet.', NULL, 'Gjenta 10 ganger på begge ben.', 1),
-- Balanseøvelser
    (14, -1, 'Vektforskyvning sidevegs', 'vektforskyvningsideveis.png', 'Stå oppreist med litt bredere plassering med bena enn normalt. Hold hendene langs siden. ','Mens bena holdes i ro; før kroppsvekten din i langsomt tempo til siden over det ene kneet. ;Bøy litt i kneet på det vektbærende benet. ;Du utfordrer balansen mer ved å strekke armene i samme retning som du lener deg. ;Før kroppsvekten langsom tilbake til midten, og så over til motsatt side.;Forestill deg at du beveger deg mellom to glassplater foran og bak deg.', NULL, 'Gjenta 5 ganger til hver side.', 2),
    (15, -1, 'Vektforskyvning framover og bakover', 'vektforskyvningframogtilbake.png', 'Stå oppreist med den ene foten foran den andre, med ca en skrittlengde mellom.','Mens bena holdes i ro\; før kroppsvekten din i langsomt tempo fram over det fremre kneet.;Bøy lett i kneet på vektbærende ben.;Du utfordrer balansen mer ved å strekke armene i samme retning som du lener deg.;Før kroppsvekten langsom tilbake til midten, og så over til bakre ben.', NULL, 'Gjenta 5 ganger, bytt så posisjon på bena og gjenta.', 2),
    (16, -1, 'Stå på linje', 'staapaalinje.png', 'Stå oppreist med siden vendt mot en stol eller kjøkkenbenken.','Plasser det ene foten rett foran den andre, slik at føttene står på en rett linje.;Se rett fremover og hold stillingen i 10 sekunder.', NULL, 'Gjenta på den andre foten.', 2),
    (17, -1, 'Steg sideveis', 'stegsideveis.png', 'Stå oppreist og se rett fram. Hold bekkenet i en nøytral stilling, hold magemusklene aktivert og med myke knær. Bruk en stol eller kjøkkenbenken som støtte ved behov.','Ta et steg tilsvarende hoftebreddes avstand, øk avstanden for mer utfordring. ;Hold hoftene og tærne vendt fremover. ;Sikre at kroppsvekten er likt fordelt på begge ben før du begynner et nytt sidesteg.', NULL, 'Gjenta 10 ganger', 2),
    (18, 0, 'Gå på tå', 'gaapaataa.png', 'Stå oppreist med siden mot en stol eller kjøkkenbenken.',';Løft hælene og ha vekten over tåballene.;Gå 10 steg framover på tærne, stødig og kontrollert.;Plasser føttene ved siden av hverandre i hoftebreddes avstand før du senker hælene kontrollert ned til gulvet.;Snu i retning mot stolen, og gjenta i motsatt retning.', NULL, 'Gjenta på den andre foten.', 2),
    (19, 0, 'Gå på linje', 'gaapaalinje.png', 'Stå oppreist med siden mot en stol eller kjøkkenbenken.','Sett et ben rett foran det andre og gå så 10 steg framover på en rett linje.;La det være en liten glipe mellom den fremre og den bakre foten i hvert steg.;Se framover og prøv å gå stødig.', NULL, 'Skift retning.', 2),
    (20, 0, 'Gå på hæl', 'gaapaahael.png', 'Stå oppreist med siden mot en stol eller kjøkkenbenken. Sørg for å være i balanse med begge ben før du begynner å gå.','Løft opp tærne og ha vekten over på hælene;Gå stødig og kontrollert i 10 steg.;Plasser føttene ved siden av hverandre i hoftebreddes avstand før du senker tærne kontrollert ned til gulvet.', NULL, NULL, 2),
    (21, 0, 'Gange bakover', 'gangebakover.png', 'Stå oppreist med siden mot en stol eller kjøkkenbenken. Hold knærne myke underveis i øvelsen. Sørg for å være i balanse med begge ben før du begynner å gå.','Gå stødig og kontrollert i 10 steg.;Ta små steg og sørg for å holde en stødig og kontrollert rytme', NULL, NULL, 2),
    (22, 0, 'Gange i 8-tall', 'gangeiaattetall.png', 'Bruk en stol som støtte og for hjelp til retning til å begynne med,','Stå bak stolen og forestill deg en sirkel rundt stolen. Forestill deg så enda en slik sirkel bak stolen, slik at du står i et senter av ett 8-tall.;Gå med korte og stødige steg rundt stolen, ta en kort pause for å sikre at du er i balanse.;Gå så den bakre sirkelen tilbake til utgangsposisjon;Etter hvert som du behersker øvelsen kan du gå begge sirklene samtidig.', NULL, NULL, 2),
    (23, 1, 'Gå på linje bakover', 'gaapaalinjebakover.png', 'Stå oppreist med siden mot en stol eller kjøkkenbenken. Hold knærne myke underveis i øvelsen. Sørg for å være i balanse med begge ben før du begynner å gå.','Plasser en fot rett bak den andre slik at tærne nesten berører hælen og slik at du går bakover på en rett linje.;Gå stødig og kontrollert i 10 steg.;Ta små steg og sørg for å holde en stødig og kontrollert rytme', NULL, NULL, 2),
    (24, 1, 'Steg fram, til siden, bak, i variert mønster', 'stegimoenster.png','Stå oppreist med hoftebreddes avstand mellom føttene. Hold overkroppen i en nøytral posisjon, og se rett fram. Unngå å låse kneet ditt når du skyver deg tilbake til utgangsposisjonen.','Flytt ett og ett ben i ulike retninger som illustrert.;Øvelsen gjennomføres i langsomt tempo, og økes etter hvert som du behersker det.;Kjenn at du har kontroll gjennom hele øvelsen.', NULL, 'Gjenta på den andre foten.', 2),
    (25, 1, 'Utfall, balanse, forover og sidelengs', 'utfallbalanse.png', 'Stå oppreist med hoftebreddes avstand mellom føttene. Hold overkroppen i en nøytral posisjon, og se rett fram. Unngå å låse kneet ditt når du skyver deg tilbake til utgangsposisjonen.','• Ta ett steg forover med det ytterste benet, plasser foten flatt på gulvet og med bøyd kne.;Skyv lett i fra med denne foten og bring benet kontrollert tilbake til utgangsposisjonen.;Ta en liten pause og kjenn at du er i balanse. Gjenta øvelsen med det andre benet.;Ta så et steg ut til siden med det ytterste benet, plasser foten på gulvet og med bøyd kne.;Skyv lett i fra med denne foten og bring benet kontrollert tilbake til utgangsposisjonen.;Ta en liten pause og kjenn at du er i balanse. Gjenta øvelsen med det andre benet.', NULL, 'Gjenta 10 ganger på hvert ben og i hver retning.', 2);

--re-insert the stuff that depended on exercises, adapted to fit the new exercises.
INSERT INTO `ExerciseGroups` (`exerciseGroupID`, `exerciseGroupName`, `exerciseType`) VALUES
(1, 'Styrke øvelser', 1),
(2, 'Balanse øvelser', 0);

INSERT INTO `FeedbackMsgDefault` (`msgID`, `feedbackText`, `timeCreated`, `category`, `AIFeedbackType`, `idx`, `balanceExerciseID`, `strengthExerciseID`) VALUES
(1, 'Standardråd for lav BI', '2016-06-01 00:00:00', 1, NULL, -1, 16, 4),
(2, 'Standardråd for middels BI', '2016-06-01 00:00:00', 1, NULL, 0, 19, 7),
(3, 'Standardråd for høy BI', '2016-06-01 00:00:00', 1, NULL, 1, 23, 11),
(4, 'Standard aktivitetstips om å sitte mindre (AI=0)', '2016-06-01 00:00:00', 0, 0, 0, NULL, NULL),
(5, 'Standard aktivitetstips om å sitte mindre (AI=1)', '2016-06-01 00:00:00', 0, 0, 1, NULL, NULL),
(6, 'Standard aktivitetstips om å sitte mindre (AI=2)', '2016-06-01 00:00:00', 0, 0, 2, NULL, NULL),
(7, 'Standard aktivitetstips om å sitte mindre (AI=3)', '2016-06-01 00:00:00', 0, 0, 3, NULL, NULL),
(8, 'Standard aktivitetstips om å sitte mindre (AI=4)', '2016-06-01 00:00:00', 0, 0, 4, NULL, NULL),
(9, 'Standard aktivitetstips om å sitte mindre (AI=5)', '2016-06-01 00:00:00', 0, 0, 5, NULL, NULL),
(10, 'Standard aktivitetstips om å gå mer (AI=0)', '2016-06-01 00:00:00', 0, 1, 0, NULL, NULL),
(11, 'Standard aktivitetstips om å gå mer (AI=1)', '2016-06-01 00:00:00', 0, 1, 1, NULL, NULL),
(12, 'Standard aktivitetstips om å gå mer (AI=2)', '2016-06-01 00:00:00', 0, 1, 2, NULL, NULL),
(13, 'Standard aktivitetstips om å gå mer (AI=3)', '2016-06-01 00:00:00', 0, 1, 3, NULL, NULL),
(14, 'Standard aktivitetstips om å gå mer (AI=4)', '2016-06-01 00:00:00', 0, 1, 4, NULL, NULL),
(15, 'Standard aktivitetstips om å gå mer (AI=5)', '2016-06-01 00:00:00', 0, 1, 5, NULL, NULL);


